# Generated by Django 3.1.7 on 2021-03-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='links',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
